apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workshop-app.fullname" . }}
  labels:
    {{- include "workshop-app.labels" . | nindent 4 }}
data:
  app.json: |
    {
      "title": {{ .Values.config.title | quote }},
      "theme_color": {{ .Values.config.theme_color | quote }},
      "message": {{ .Values.config.message | quote }}
    }
